name: Sync main to Bundled-main

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  sync-branch:
    name: Update Bundled-main from main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: connor-baer/action-sync-branch@b54ed9b2c68941d1b2974a7776dc8e3d7d14073c
        with:
          branch: Bundled-main
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false
